Repository cse110-sp24-group11/cse110-sp24-group11, pull requests merged in 2024-06, with the labels that each got.

#31 Projects Page
  assets/recurring-elements/footer.js
  assets/recurring-elements/nav.css
  assets/src/calendar/style.css
  assets/src/front-page/style.css
  assets/src/journal/style.css
  assets/src/projects/importProjects.js
  assets/src/projects/index.html
  assets/src/projects/projectCRUD/cProject.js
  assets/src/projects/projectCRUD/rProject.js
  assets/src/projects/projectCRUD/uProject.js
  assets/src/projects/style.css
Labels: enhancement

#35 Homepage Development
  assets/src/front-page/design-notes.md
  assets/src/front-page/index.html
  assets/src/front-page/journal.js
  assets/src/front-page/project.js
  assets/src/front-page/style.css
  assets/src/front-page/task.js
Labels: enhancement

#47 Projects quality of life
  assets/docs/global.html
  assets/docs/index.html
  assets/docs/journal_updateJournal.js.html
  assets/docs/projects_importProjects.js.html
  assets/docs/projects_projectCRUD_addButton.js.html
  assets/docs/projects_projectCRUD_cProject.js.html
  assets/docs/projects_projectCRUD_rProject.js.html
  assets/docs/projects_projectCRUD_uProject.js.html
  assets/docs/script.js.html
  assets/src/projects/projectCRUD/cProject.js
  assets/src/projects/projectCRUD/uProject.js
Labels: enhancement

#51 Homepage Functionality and Documentation
  assets/src/front-page/design-notes.md
  assets/src/front-page/index.html
  assets/src/front-page/journal.js
  assets/src/front-page/project.js
  assets/src/front-page/style.css
  assets/src/front-page/task.js
Labels: documentation, enhancement

#65 Bug Fix for invalid EndDate
  assets/docs/-_Lexer.html
  assets/docs/-_Parser.html
  assets/docs/-_Renderer.html
  assets/docs/-_TextRenderer.html
  assets/docs/-_Tokenizer.html
  assets/docs/calendar_script.js.html
  assets/docs/front-page_journal.js.html
  assets/docs/global.html
  assets/docs/index.html
  assets/docs/journal_updateJournal.js.html
  assets/docs/md-previewer_marked.esm.js.html
  assets/docs/projects_importProjects.js.html
  assets/docs/projects_projectCRUD_addButton.js.html
  assets/docs/projects_projectCRUD_cProject.js.html
  assets/docs/projects_projectCRUD_rProject.js.html
  assets/docs/projects_projectCRUD_uProject.js.html
  assets/src/calendar/script.js
Labels: bug
